### ISSUE TITLE
Policy Manual Project Proposal

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/policy-wg#74]
For the Policy Manual Project, @mrchrisadams needs to submit a proposal using the [New Project Proposal issue template](https://github.com/Green-Software-Foundation/oc/issues/new?assignees=tmcclell%2C+Sealjay%2C+seanmcilroy29&labels=project%2C+proposed&projects=&template=new-project-proposal.md&title=%5BProject%5D+Title+Of+Project).

**Comment by NAMRATA-WOKE** [comment]
@mrchrisadams plugged in some answers for you. Last few would love your thoughts + @lisamcnally @muemich and everyone else!

**Working Title**: Policy Manual

**Related issues or discussions**:

https://github.com/Green-Software-Foundation/policy-wg/issues/69

**Tagline**: A digital manual on new regulations on greening software

**Abstract**: Manual highlighting the new regulations related to greening software and emissions/impact reporting, and what companies will be held accountable for and when.

**Quote**: 

_"The Policy Manual from the GSF arrives at a pivotal moment. As we face a surge of new environmental legislation, navigating the complexities of greening software and emissions reporting is increasingly daunting. This comprehensive resource equips us to address environmental impacts proactively and ensure compliance with evolving standards."_

**Audience**: 

- CTOs
- CIOs
- CSOs
- Software Engineers

**ToC**: 

The Policy Manual will help with building knowledge and tooling to improve impact measurement. 

**Governance**: Which working group(s) do you think should govern this project?

- [ ] Community
- [ ] Open Source
- [X] Policy
- [ ] Standards

**Operating Model:** Will this project operate based on:

- [ ] Consensus - Goal is everyone agree to every change so we are speaking with one voice when the deliverable is released.
- [X] Maintainers - The Project Leads listen to feedback and incorporate it back into the project if they see fit. 

**Problem**: List 3-5 problems this audience has that this project will attempt to address. Describe Why is this project better at solving a problem compared to parallel proposals or implemented projects? **MAX 200 WORDS**


1. CTOs, CIOs, and CSOs face challenges in keeping up with evolving environmental regulations. This project clarifies greening software and emissions reporting rules, ensuring adherence to laws.
2. Many tech leaders are unaware of their software's environmental impacts and reporting obligations. This initiative educates them on environmental consequences and accurate emissions reporting's significance.
3. Aligning environmental goals with business strategy poses a hurdle for tech executives. This project offers practical operational guidance to integrate new policy requirements seamlessly.

**Solution**: Try to make this as detailed as possible. The topics given below are just suggestions; address them only if they are relevant to your problem:
- Rough design and scenarios on the probable effects, if any.
- The use of diagrams is encouraged to elucidate concepts.
- Address any possible objections.
- Explain how the solution solves each of the problems listed in the problem section.

**Closure**: How do we know that the project succeeded? This has to be measurable if possible. Make references to successor projects, if any.

**FAQ**: Add anything here that doesn't fit into the above sections. It can be blank, to begin with; as questions are asked and points clarified use this section to document those clarifications.

**Comment by mrchrisadams** [comment]
Thanks @NAMRATA-WOKE - I've created a WIP submission here for us to review in the policy WG.

https://github.com/Green-Software-Foundation/oc/issues/82

I'm not sure what creating a project formally entails at present, and I realise some wiki tools can make it easier to contribute. If there's a page I can try sharing or working on with others, I'd be very happy to do so, and move the content there too while we work on it.

**Comment by NAMRATA-WOKE** [comment]
@mrchrisadams thank you so much! @Sophietn can you please chime in here and provide some guidance?

**Comment by Sophietn** [comment]
Hi @mrchrisadams 

Thanks for submitting a new project proposal! 
The next step is to continue to discuss this project proposal with the chosen WG (policy WG) and when ready, pass this project proposal through the Policy WG as a Motion. eg. Motion to agree project launch - any objections? 
cc @seanmcilroy29 please add to a future agenda. 
Once the motion has past, the GSF will create a new Github repo to house the project and discussions as they evolve. 
We have a checklist to follow through all the setup steps, which I will create in Wiki and share with you.

**Comment by NAMRATA-WOKE** [comment]
@Sophietn the PWG has already approved this project.

**Comment by seanmcilroy29** [comment]
## Two Proposals

**Group Discussion Call:** Host an org-wide call facilitated by the PWG where we focus on the Policy Manual, define desired outcomes, and outline actionable steps.

**Individual Outreach:** Divide responsibilities to connect with member organizations individually. This approach may help us dive deeper into individual org needs, and how they are adjusting/responding to changing legislation.

### Chris's Comments
Of the two, I’d appreciate a variant of the first one - having a smaller working group to translate some of the initial proposal into some shorter term goals would make sense, and ideally try to aim for getting some of those set up first, before opening it up more widely.
I think you, JB and others on this email chain already have enough context for us to have a productive meeting, and the proposal has already been shared in the policy WG once - I think a small group call where there’s already some trust and context there is more likely to lead us to finished, and updated version of what’s visible here, that we could realistically deliver in a first phase (it could definitely do with a bit more love)

https://github.com/Green-Software-Foundation/projects/issues/82#issuecomment-2006581869

**Committing time**
From my time, it would be really helpful if we could have a honest discussion about what’s realistic to ask for in terms of staff time at the GSF level, and the how much capacity from GSF members we know we’re able to commit, and I’d feel more able to speak freely if it wasn’t recorded like our policy WG working group calls are. Would that be possible?

**Opening it wider afterwards**
Once we have a clearer idea of the time we’re able to contribute, and some of the shorter term goals, I think it would be great to open it wider to speak to more member organisations.

### Lisa's Comments
**Group Discussion Call:** Host an org-wide call facilitated by the PWG where we focus on the Policy Manual, define desired outcomes, and outline actionable steps. I agree with Chris that if we host something so broadly, we may not get as much engagement or commitment across the group. So, could we plan to outline steps with a selection of interested members (those on the email plus any others we think should at least be invited to participate given that they are leads of working groups, for example)?
Similar to what Chris proposed, after we do our deeper dive exercise with the smaller group, then we should consider doing an org-wide read-out to solicit any remaining feedback or capture any additional interest. If we do receive additional interest when we do this broader read-out, then we could offer to do what you suggest below, which is to set up 1:1's with any additional folks who might be interested in participating in policy manual development.

**Individual Outreach:** Divide responsibilities to connect with member organizations individually. This approach may help us dive deeper into individual org needs, and how they are adjusting/responding to changing legislation.

**Committing time** - Agree about honest discussion and non-recording, which means I'm also open to meeting at a different time than our regularly scheduled PWG times. 

Action Item - Scheduling time (different from our PWG schedule) with everyone on this email chain so we can start discussing and carving out actions! :) 

### Michael's Comments
I do think that a mix of Option 1 and Option 2 will be best like Chris and Lisa proposed.
If possible, let's schedule a call outside of Monday with interested members. I personally don't mind recording but agree that a non-recorded meeting will be more open and might lead to better discussions.

### Asim's Comments
One model that's worked very well for the patterns project (and I think is something I'd like to package up as an optional way of working for other projects) is holding a series of workshops with a small set of people and a design thinking consultant.

- The leads work with our consultant to design a workshop, outcomes, questions, ideal deliverable etc... 
- Our consultant designs a series of workshops.
The leads decide who to include (this can't be a very large group, limited places, need some fair way of making sure those spaces are filled).
- People join those workshops and through a facilitated set of calls (and perhaps some async work as well) we end up with a deliverable.
- It is a larger commitment from the people who want to join, it's a huge waste if someone joins the first call and then skips the rest. Perhaps it should be an application process, you apply to join the workshop and there is a review process to decide the best people. 
- But the outcome is a lot clearer, you always end up with something that at least is the consensus view of a commited set of people.
[@Chris Adams](mailto:chris@thegreenwebfoundation.org) in terms of commitment from the GSF we can commit a consultant plus any time from our writer/designer to create assets from the results. The result of these workshops so far have been Miro boards, so there is some effort after to write it all up, can support there as well.

Note since this has to be a consensus project, post this workshop effort, whatever the [deliverable.is](http://deliverable.is/) should also go out to the broader policy WG for a period of time (2 weeks) to hunt for objections and once those are resolved it has to go to the SC for ratification.

**Comment by mrchrisadams** [comment]
I have updated the this issue with an updated, and somewhat pared back "Policy Radar" proposal, 

https://github.com/Green-Software-Foundation/projects/issues/82

**Comment by seanmcilroy29** [comment]
Invite NTT Data to offer some direction on how to draft a Policy Radar
