### ISSUE TITLE
2024-07-08

### ISSUE THREAD

**Issue by mrchrisadams** [Green-Software-Foundation/policy-wg#86]
# 2024 07 08

Time 0830 PDT / 1630 BST - See the time in your timezone https://everytimezone.com/s/a8399b00

- Chair – Chris Adams (The Green Web Foundation)
- Chair - Lisa.McNally (Thoughtworks)
- Chair - Michael Mueller (re:cinq)
- Convener –  Sean Mcilroy (Linux Foundation)
***
## Antitrust Policy

Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.
***
### Recordings

The Working Group Meeting is [recorded](https://docs.google.com/document/d/1ttKxQE6GweNAI1TCfIq-Fgbv6WIEIuDRbLnIP1ZJ5N8/edit) and is available for members to review until the next scheduled meeting.
***
### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, GitHub username (optional)
***
## Agenda
- [ ] Approve Agenda / [previous minutes](#85 )

### Actions from the previous minutes:

_these might be repeated below in our discussions - if not they're candidated for the next meeting_

- [x] Contact BCS to schedule a follow-up meeting on MOU for August 5th.  
- [x] Investigate existing policy radar frameworks for potential adoption.  
- [x] Circulate presentation on proposed GSF reorganisation to working group members for feedback.  
- [x] Schedule cross-working group collaboration discussions between GSF and other Linux Foundation sustainability projects.  
- [x] Clarify the scope and goals of potential certification for Software Carbon Intensity estimates.

***
## Discussions

 - [x] **Revisiting the [MOU with the BCS](https://docs.google.com/document/d/1oyJawJYs5XuCA6IOdDb7BjmJGzmUNJ9FNNVRxiersD8/edit)** - an update, and deciding to dedicate time to discuss this outside this meeting to bring back if need be. 
   - AI - Contact BCS to schedule a follow-up meeting on MOU for August 5th.
 - [x] **Inviting Gadhu from NTT DATA to discuss their policy implementation approach** - decide to find a time or move forward without this if hearing from them is no longer possible. - Sean
- [ ] [Review and Close Issues ](https://github.com/Green-Software-Foundation/policy-wg/issues)

***
## Sustainable Foundation LF Foundation Round Table Proposal - Sean
- [x] Discussions with fellow foundations to understand their primary focused areas.
  - LF Carbon Accounting Initiatives - https://docs.google.com/document/d/11wyOjA_w6TD0aQ31BN-dAFBqPYJENpDsi43H54mMWzI/edit#heading=h.tkinzqi20r20
  - Next meeting - 23rd July
***
## AOB
- [x] GSF Off-site to outline GSF evolution
  - Policy WG feedback
***
## Next meeting 
- [x] 22nd July
***
## Adjourn 
- [x] Motion to adjourn
--------

**Comment by seanmcilroy29** [comment]
Attended

**Comment by mrchrisadams** [comment]
Attended

**Comment by seanmcilroy29** [comment]
MoM
Chris opens the meeting at 0830 PDT / 1630 BST
GSF Policy WG

**Green software standards and collaboration between GSF and BCS.**
Sean Mcilroy provides an update on the GSF, including a follow-up meeting with BCS and a discussion of an MOU.
Chris clarifies the BCS's role and interest in collaborating with the GSF rather than joining as a member.
Chris and Sean discuss the potential for collaboration between the Green Software Foundation and the BCS.
The Green Software Foundation's openly licensed ISO standard for software carbon intensity may be an area of collaboration.

**Collaborating with the British Computer Society for sustainable software development.**
Sean outlined a plan to collaborate with Alex from BCS on a Memorandum of Understanding (MOU). Chris has proposed creating a "GSF policy radar" to track new legislation that impacts green software reporting. Chris and Sean have discussed creating a shared calendar of policy interventions to stay informed and respond to laws in various regions. NTTData has been mentioned as a potential partner for collaboration, with Namrata being in touch with them to explore how to contribute or plug into their work.

**Upcoming regulations for sustainable software practices and their impact on organizations.**
"Sanjay and his team analyze regulations for clients, identifying which ones will impact them and when. They assist clients in preparing for compliance by focusing on timelines and readiness. Sanjay and Chris emphasize the importance of understanding upcoming regulations in order to implement sustainable software practices."

**Sharing information about upcoming laws and their implications for compliance.**
Kunal and Chris are discussing how to share policy knowledge and collaborate among team members. They are considering creating a shared calendar or a list of deadlines for policy updates. Chris is suggesting creating a wiki or a sharing platform to centralize information on upcoming laws and regulations. Sanjay has agreed to review the information and discuss the group's ability to share it during the next working session on July 23rd.

**Creating a tool to track legislation timelines and dates.**
Sean and Chris are talking about the challenges they face in collaborating on a project because of corporate policies and restricted tools. They're also discussing potential solutions for a legislation tracking platform, such as using GitHub templates and populating information from a Policy Working Group. Sean is collaborating with other foundations, including CNC, to develop an architecture for the platform.

**Sustainability initiatives and policy working group collaboration.**
Sean and Chris discuss GSF's role in sustainability, policy, and collaboration with other foundations.
Kunal clarifies EDS's concerns about GSF's ask and the potential for duplication of effort. Sean provides update on sustainability initiatives, faces technical difficulties. Sean suggests dedicating more effort and resources to the policy working group to drive initiatives and mitigate legislation. Asim believes the policy working group should be a standards organization for green software, with the potential for collaboration with the standards working group.

**Upcoming policy changes and their potential impact on organizations.**
Organizations aim to work together to address potential policies and laws affecting their interests. Sean McIlroy and Chris Adams are discussing the policy radar and upcoming meetings.

**Action Items**
- [ ] @Sean Mcilroy - Circulate the draft BCS MOU to the policy working group for final review. Invite Alex from BCS for further discussions if there are no objections.
- [ ] @Sean Mcilroy - Provide a further update on discussions with other sustainability foundations at the next policy working group meeting on July 22nd.
- [ ] @Sean Mcilroy - Drive additional focus and resources into the policy and standards working groups via upcoming steering committee discussions.
- [ ] Circle back internally at NTT Data to understand what regulatory policy information could be shared to inform the GSF's policy radar.

**Comment by seanmcilroy29** [comment]
Approved
